const canvas = document.querySelector("#game");
const ctx = canvas.getContext("2d");

const ui = {
  mainMenu: document.querySelector("#mainMenu"),
  mobileControls: document.querySelector("#mobileControls"),
  mobileStick: document.querySelector("#mobileStick"),
  mobileStickKnob: document.querySelector("#mobileStickKnob"),
  playerNameInput: document.querySelector("#playerNameInput"),
  connectPlayer: document.querySelector("#connectPlayer"),
  launchGame: document.querySelector("#launchGame"),
  openTutorial: document.querySelector("#openTutorial"),
  metaFragments: document.querySelector("#metaFragments"),
  metaPackCost: document.querySelector("#metaPackCost"),
  buyMetaPack: document.querySelector("#buyMetaPack"),
  metaPackResult: document.querySelector("#metaPackResult"),
  metaUpgradeSummary: document.querySelector("#metaUpgradeSummary"),
  tutorial: document.querySelector("#tutorial"),
  tutorialSpotlight: document.querySelector("#tutorialSpotlight"),
  tutorialCard: document.querySelector("#tutorialCard"),
  tutorialKicker: document.querySelector("#tutorialKicker"),
  tutorialTitle: document.querySelector("#tutorialTitle"),
  tutorialText: document.querySelector("#tutorialText"),
  tutorialProgress: document.querySelector("#tutorialProgress"),
  closeTutorial: document.querySelector("#closeTutorial"),
  skipTutorial: document.querySelector("#skipTutorial"),
  menuPlayerName: document.querySelector("#menuPlayerName"),
  characterSelect: document.querySelector("#characterSelect"),
  characterChoices: document.querySelector("#characterChoices"),
  playerNameHud: document.querySelector("#playerNameHud"),
  wave: document.querySelector("#wave"),
  hp: document.querySelector("#hp"),
  money: document.querySelector("#money"),
  goldMultiplier: document.querySelector("#goldMultiplier"),
  enemyCount: document.querySelector("#enemyCount"),
  hand: document.querySelector("#hand"),
  handRank: document.querySelector("#handRank"),
  suits: document.querySelector("#suits"),
  controlsTip: document.querySelector("#controlsTip"),
  weapons: document.querySelector("#weapons"),
  dpsHint: document.querySelector("#dpsHint"),
  shop: document.querySelector("#shop"),
  shopHand: document.querySelector("#shopHand"),
  shopSlots: document.querySelector("#shopSlots"),
  shopGold: document.querySelector("#shopGold"),
  shopGoldMultiplier: document.querySelector("#shopGoldMultiplier"),
  shopRunInfo: document.querySelector("#shopRunInfo"),
  weaponCompare: document.querySelector("#weaponCompare"),
  packChoiceTitle: document.querySelector("#packChoiceTitle"),
  packOffer: document.querySelector("#packOffer"),
  rerollShop: document.querySelector("#rerollShop"),
  startWave: document.querySelector("#startWave"),
  godMode: document.querySelector("#godMode"),
  godCountdown: document.querySelector("#godCountdown"),
  gameOver: document.querySelector("#gameOver"),
  finalScore: document.querySelector("#finalScore"),
  fragmentReward: document.querySelector("#fragmentReward"),
  restart: document.querySelector("#restart"),
};


